version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    networks:
      - inception

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_ADMIN_PASS: changeme
      WORDPRESS_ADMIN: acoste
      WORDPRESS_USER: test
      WORDPRESS_USER_PASS: changeme
      MYSQL_DATABASE: wordpress
    networks:
      - inception

  mariadb:
    image: mariadb:10.6
#    command: --log-warnings=1 --silent-startup #or   command: --innodb-use-native-aio=0 mute log startup
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    networks:
      - inception

volumes:
  wordpress_data:
      driver_opts:
        type: none
        o: bind
        device: ${PWD}/../acoste/data/wordpress
  db_data:
      driver_opts:
        type: none
        o: bind
        device: ${PWD}/../acoste/data/mariadb

networks:
  inception:

